### ISSUE TITLE
Add utility for retrieving full import paths  

### ISSUE THREAD

**Issue by makspll** [Enselic/rustdoc-json#1]
As discussed in here: https://github.com/rust-lang/rust/issues/104651#issuecomment-1328115787

It would be useful to provide a utility function to retrieve import paths for items.

**Comment by Enselic** [comment]
Hmm how did you end up in this abandoned git repo? Did I forget to update some link somewhere?

In any case, there was a misunderstanding, see https://github.com/rust-lang/rust/issues/104651#issuecomment-1328294038 🙂

**Comment by makspll** [comment]
haha, I have no idea, must have been tired
